### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bitbacchus** [selinaZitrone/YoMos2020#2]
- [ ] change the name to something more general
- [ ] update readme
- [ ] have a look at the `drake` package and possibly include it
- [ ] move all but the rendered files from gh_pages back to the master branch
- [ ] have another look at the Turing way book for more inspiration
- [x] add roxygen2 for documentation of functions and data
- [x] maybe include piggyback package to include large datasets in a package on Github

**Comment by selinaZitrone** [comment]
- [ ] add roxygen2 for documentation of functions and data

**Comment by bitbacchus** [comment]
> * [ ]  add roxygen2 for documentation of functions and data

just edit my comment, this way we have a single task list

**Comment by bitbacchus** [comment]
FYI: https://gitlab.gwdg.de/shanss/yomos2020 is work-in-progress of the GitLab version

Feel free to login and ask for access there.

**Comment by selinaZitrone** [comment]
[ ] maybe include `piggyback` package to include large datasets in a package on Github
